name: Deploy to GitHub Pages

on:
  # Run automatically when you push to the `main` branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# This is the new section that grants the workflow permissions
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repository
        uses: actions/checkout@v4

      - name: Install, build, and deploy
        uses: withastro/action@v2
